In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.Series([0.25, 0.5, 0.75, 1.0])
data

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

In [3]:
data.values

array([0.25, 0.5 , 0.75, 1.  ])

In [4]:
data.index

RangeIndex(start=0, stop=4, step=1)

In [5]:
data[1]

0.5

In [6]:
data[1:3]

1    0.50
2    0.75
dtype: float64

### `Series` as generalized NumPy array

In [7]:
data = pd.Series([0.25, 0.5, 0.75, 1.0], index=['a', 'b', 'c', 'd'])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [8]:
data['b']

0.5

In [9]:
data = pd.Series([0.25, 0.5, 0.75, 1.0], index=[2, 5, 3, 7])
data

2    0.25
5    0.50
3    0.75
7    1.00
dtype: float64

In [10]:
data[5]

0.5

### Series as specialized dictionary

In [11]:
population_dict = {'California': 38332521,
                   'Texas': 26448193,
                   'New York': 19651127,
                   'Florida': 19552860,
                   'Illinois': 12882135}
population = pd.Series(population_dict)
population

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

In [12]:
population['California']

38332521

In [13]:
population["California":"New York"]

California    38332521
Texas         26448193
New York      19651127
dtype: int64

### Constructing Series Object

```python
>>> pd.Series(data, index=index)
```

In [14]:
pd.Series([2, 4, 6])

0    2
1    4
2    6
dtype: int64

In [15]:
pd.Series(5, index=[100, 200, 300])

100    5
200    5
300    5
dtype: int64

In [16]:
pd.Series({2:'a', 1:'b', 3:'c'})

2    a
1    b
3    c
dtype: object

In [17]:
pd.Series({2:'a', 1:'b', 3:'c'}, index=[3, 2])

3    c
2    a
dtype: object

## The Pandas DataFrame Object

### DataFrame as a generalized NumPy array

In [19]:
area_dict = {'California': 423967, 'Texas': 695662, 'New York': 141297, 'Florida': 170312, 'Illinois': 149995}
area = pd.Series(area_dict)
area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
dtype: int64

In [20]:
states = pd.DataFrame({'population': population, 'area':area})
states

population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297
Florida       19552860  170312
Illinois      12882135  149995

In [30]:
states.index

Index(['California', 'Texas', 'New York', 'Florida', 'Illinois'], dtype='object')

In [28]:
states.columns

Index(['population', 'area'], dtype='object')

### DataFrame as specialized dictionary

In [31]:
states.area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

### Constructing DataFrame objects

#### From a single Series object

In [32]:
pd.DataFrame(population, columns=['population'])

population
California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135

In [36]:
data = [{'a': i, 'b': 2 * i, 'c': 2 ** i} for i in range(5)]
pd.DataFrame(data)

a  b   c
0  0  0   1
1  1  2   2
2  2  4   4
3  3  6   8
4  4  8  16

In [37]:
pd.DataFrame([{'a':1, 'b':2}, {'b':3, 'c':4}])

a  b    c
0  1.0  2  NaN
1  NaN  3  4.0

#### From a dictionary of Series objects

In [39]:
pd.DataFrame({'population': population, 'area': area})

population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297
Florida       19552860  170312
Illinois      12882135  149995

#### From a two-dimensional NumPy array

In [176]:
rand = np.random.RandomState(42)
pd.DataFrame(rand.rand(3,2), columns=['foo', 'bar'], index=['a', 'b', 'c'])

foo       bar
a  0.374540  0.950714
b  0.731994  0.598658
c  0.156019  0.155995

#### From a NumPy structured array

In [117]:
A = np.zeros(3, dtype=[('A', 'i8'), ('B', 'f8')])
A

array([(0, 0.), (0, 0.), (0, 0.)], dtype=[('A', '<i8'), ('B', '<f8')])

In [118]:
pd.DataFrame(A)

A    B
0  0  0.0
1  0  0.0
2  0  0.0

## The Pandas Index Object

In [119]:
ind = pd.Index([2, 3, 5, 7, 11])
ind

Int64Index([2, 3, 5, 7, 11], dtype='int64')

In [120]:
ind[1]

3

In [121]:
ind[::2]

Int64Index([2, 5, 11], dtype='int64')

In [122]:
print("size  =", ind.size)
print("shape =", ind.shape)
print("ndim  =", ind.ndim)
print("dtype =", ind.dtype)

size  = 5
shape = (5,)
ndim  = 1
dtype = int64


### Index as ordered set

In [123]:
indA = pd.Index([1, 3, 5, 7, 9])
indB = pd.Index([2, 3, 5, 7, 11])

In [124]:
indA & indB

C:\Users\gprab\AppData\Local\Temp\ipykernel_16952\144964795.py:1: FutureWarning: Index.__and__ operating as a set operation is deprecated, in the future this will be a logical operation matching Series.__and__.  Use index.intersection(other) instead.
  indA & indB


Int64Index([3, 5, 7], dtype='int64')

In [125]:
indA | indB

C:\Users\gprab\AppData\Local\Temp\ipykernel_16952\3251124211.py:1: FutureWarning: Index.__or__ operating as a set operation is deprecated, in the future this will be a logical operation matching Series.__or__.  Use index.union(other) instead.
  indA | indB


Int64Index([1, 2, 3, 5, 7, 9, 11], dtype='int64')

In [126]:
indA ^ indB

C:\Users\gprab\AppData\Local\Temp\ipykernel_16952\2832893868.py:1: FutureWarning: Index.__xor__ operating as a set operation is deprecated, in the future this will be a logical operation matching Series.__xor__.  Use index.symmetric_difference(other) instead.
  indA ^ indB


Int64Index([1, 2, 9, 11], dtype='int64')

## Data Indexing and Selection

### Data Selection in Series

#### Series as Dictionary

In [127]:
data = pd.Series([0.25, 0.5, 0.75, 1.0], index=['a', 'b', 'c', 'd'])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [128]:
data['b']

0.5

In [129]:
'a' in data

True

In [130]:
data.keys()

Index(['a', 'b', 'c', 'd'], dtype='object')

In [131]:
list(data.items())

[('a', 0.25), ('b', 0.5), ('c', 0.75), ('d', 1.0)]

In [132]:
data['e'] = 1.25

In [133]:
data

a    0.25
b    0.50
c    0.75
d    1.00
e    1.25
dtype: float64

### Series as one-dimensional array

In [134]:
data['a':'c']

a    0.25
b    0.50
c    0.75
dtype: float64

In [135]:
data[0:2]

a    0.25
b    0.50
dtype: float64

In [136]:
data[(data > 0.3) & (data < 0.8)]

b    0.50
c    0.75
dtype: float64

In [137]:
data[['a', 'e']]

a    0.25
e    1.25
dtype: float64

### Indexers: loc and iloc

In [138]:
data = pd.Series(['a', 'b', 'c'], index=[1, 3, 5])
data

1    a
3    b
5    c
dtype: object

In [139]:
data[1]

'a'

In [140]:
data[1:3]

3    b
5    c
dtype: object

In [141]:
data.loc[1]

'a'

In [142]:
data.loc[1:3]

1    a
3    b
dtype: object

In [143]:
data.iloc[1]

'b'

In [144]:
data.iloc[1:3]

3    b
5    c
dtype: object

## Data Selection in DataFrame

### DataFrame as a dictionary

In [145]:
area = pd.Series({'California': 423967, 'Texas': 695662,
                  'New York': 141297, 'Florida': 170312,
                  'Illinois': 149995})
pop = pd.Series({'California': 38332521, 'Texas': 26448193,
                 'New York': 19651127, 'Florida': 19552860,
                 'Illinois': 12882135})
data = pd.DataFrame({'area':area, 'pop':pop})
data

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127
Florida     170312  19552860
Illinois    149995  12882135

In [146]:
data['area']

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [147]:
data.area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [148]:
data.area is data['area']

True

In [149]:
data.pop is data['pop']

False

In [150]:
data['density'] = data['pop'] / data['area']
data

area       pop     density
California  423967  38332521   90.413926
Texas       695662  26448193   38.018740
New York    141297  19651127  139.076746
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763

### DataFrame as two-dimensional array

In [151]:
data.values

array([[4.23967000e+05, 3.83325210e+07, 9.04139261e+01],
       [6.95662000e+05, 2.64481930e+07, 3.80187404e+01],
       [1.41297000e+05, 1.96511270e+07, 1.39076746e+02],
       [1.70312000e+05, 1.95528600e+07, 1.14806121e+02],
       [1.49995000e+05, 1.28821350e+07, 8.58837628e+01]])

In [152]:
data.T

California         Texas      New York       Florida      Illinois
area     4.239670e+05  6.956620e+05  1.412970e+05  1.703120e+05  1.499950e+05
pop      3.833252e+07  2.644819e+07  1.965113e+07  1.955286e+07  1.288214e+07
density  9.041393e+01  3.801874e+01  1.390767e+02  1.148061e+02  8.588376e+01

In [153]:
data.values[0]

array([4.23967000e+05, 3.83325210e+07, 9.04139261e+01])

In [154]:
data['area']

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [155]:
data.iloc[:3, :2]

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127

In [156]:
data.loc[:'New York', :"pop"]

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127

In [157]:
data.loc[data.density > 100, ['pop', 'density']]

pop     density
New York  19651127  139.076746
Florida   19552860  114.806121

In [158]:
data.iloc[0, 2] = 90
data

area       pop     density
California  423967  38332521   90.000000
Texas       695662  26448193   38.018740
New York    141297  19651127  139.076746
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763

### Additional indexing conventions

In [159]:
data['New York':'Illinois']

area       pop     density
New York  141297  19651127  139.076746
Florida   170312  19552860  114.806121
Illinois  149995  12882135   85.883763

In [160]:
data[1:3]

area       pop     density
Texas     695662  26448193   38.018740
New York  141297  19651127  139.076746

In [161]:
data[data.density > 100]

area       pop     density
New York  141297  19651127  139.076746
Florida   170312  19552860  114.806121

## Operating on Data in Pandas

### Ufuncs: Index Preservation

In [196]:
rand = np.random.RandomState(23)
ser = pd.Series(rand.randint(0, 10, 4))
ser

0    3
1    6
2    8
3    9
dtype: int32

In [205]:
df = pd.DataFrame(np.random.RandomState(32).randint(0, 10, (3, 4)), columns=['A', 'B', 'C', 'D'])
df

A  B  C  D
0  7  5  6  8
1  3  7  9  3
2  5  9  4  1

In [207]:
np.exp(ser)

0      20.085537
1     403.428793
2    2980.957987
3    8103.083928
dtype: float64

In [208]:
np.sin(df * np.pi / 4)

A         B             C             D
0 -0.707107 -0.707107 -1.000000e+00 -2.449294e-16
1  0.707107 -0.707107  7.071068e-01  7.071068e-01
2 -0.707107  0.707107  1.224647e-16  7.071068e-01

## UFuncs Index Alignment

### Index Alignment in Series